/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#393942",
        "on-primary-fixed-variant": "#3e3c8f",
        "on-error-container": "#93000a",
        background: "#f8f9ff",
        "on-secondary-container": "#006f66",
        "on-primary-fixed": "#100563",
        "secondary-container": "#86f2e4",
        "on-background": "#0d1c2e",
        "on-surface": "#0d1c2e",
        secondary: "#006a61",
        "on-surface-variant": "#474651",
        "tertiary-fixed": "#e3e1ed",
        "secondary-fixed": "#89f5e7",
        "primary-fixed": "#e2dfff",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "surface-bright": "#f8f9ff",
        "surface-tint": "#5654a8",
        "surface-container": "#e6eeff",
        "on-tertiary-container": "#a3a3ad",
        "inverse-primary": "#c3c0ff",
        outline: "#777682",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-container": "#9c9af4",
        "inverse-surface": "#233144",
        "inverse-on-surface": "#eaf1ff",
        "outline-variant": "#c8c5d3",
        "surface-container-low": "#eff4ff",
        "on-secondary-fixed-variant": "#005049",
        "surface-dim": "#ccdbf3",
        "on-secondary-fixed": "#00201d",
        "surface-variant": "#d5e3fc",
        "surface-container-high": "#dce9ff",
        "primary-container": "#312e81",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        surface: "#f8f9ff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#c7c5d1",
        "secondary-fixed-dim": "#6bd8cb",
        "on-tertiary-fixed": "#1a1b23",
        primary: "#1a146b",
        "on-primary": "#ffffff",
        "surface-container-highest": "#d5e3fc",
        tertiary: "#23242c",
        "on-tertiary-fixed-variant": "#46464f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xxl: "80px",
        lg: "24px",
        xl: "48px",
        xs: "4px",
        md: "16px",
        "container-max": "1280px",
        unit: "8px",
        gutter: "24px",
        sm: "8px",
        margin: "32px",
      },
      fontFamily: {
        h2: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        h1: ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        h3: ["Inter", "sans-serif"],
      },
      fontSize: {
        h2: [
          "30px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        display: [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        h1: [
          "36px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-sm": [
          "14px",
          { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
        ],
        h3: [
          "24px",
          { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};